# N3+ Grammar & Vocabulary Database
# Used for auto-matching against OCR'd subtitle text

GRAMMAR_DB = [
    # ── N3 ──────────────────────────────────────────────────────────
    {
        "level": "N3",
        "pattern": "〜てしまう",
        "regex": r"[てで]しまう|[てで]しまった|[てで]しまい|ちゃう|ちゃった|じゃう|じゃった",
        "connection": "V-て形 ＋ しまう",
        "meaning": "完了·遗憾：做完了某事（常带后悔）/ ended up doing",
    },
    {
        "level": "N3",
        "pattern": "〜ようになる",
        "regex": r"ようになる|ようになった|ようになり",
        "connection": "V辞書形 / V-ない形 ＋ ようになる",
        "meaning": "变化：渐渐变得能做… / come to do, become able to",
    },
    {
        "level": "N3",
        "pattern": "〜ことになる",
        "regex": r"ことになる|ことになった|ことになり|ことになって",
        "connection": "V普通形 ＋ ことになる",
        "meaning": "（外部决定）变成…/决定了… / it has been decided that",
    },
    {
        "level": "N3",
        "pattern": "〜ことにする",
        "regex": r"ことにする|ことにした|ことにして",
        "connection": "V辞書形 / V-ない形 ＋ ことにする",
        "meaning": "（自己决定）决定做… / decide to do",
    },
    {
        "level": "N3",
        "pattern": "〜はずだ",
        "regex": r"はずだ|はずです|はずが|はずじゃ|はずも",
        "connection": "V普通形 / N の ＋ はずだ",
        "meaning": "推测·理应：应该是… / should be, supposed to",
    },
    {
        "level": "N3",
        "pattern": "〜らしい",
        "regex": r"らしい|らしく|らしかった|らしくて",
        "connection": "V普通形 / N ＋ らしい",
        "meaning": "传闻·推测：好像、听说… / seems like, apparently",
    },
    {
        "level": "N3",
        "pattern": "〜ようだ",
        "regex": r"ようだ|ようです|ような|ようで(?!す)",
        "connection": "V普通形 / N の ＋ ようだ",
        "meaning": "样子·推测：看起来好像… / seems like, looks as if",
    },
    {
        "level": "N3",
        "pattern": "〜ばよかった",
        "regex": r"ばよかった|ればよかった",
        "connection": "V-ば形 ＋ よかった",
        "meaning": "后悔：早知道就…好了 / should have done",
    },
    {
        "level": "N3",
        "pattern": "〜だけでなく",
        "regex": r"だけでなく|だけじゃなく|だけでなくて",
        "connection": "N / V普通形 ＋ だけでなく",
        "meaning": "不只是… / not only … but also",
    },
    {
        "level": "N3",
        "pattern": "〜ながら",
        "regex": r"ながら(?!も)",
        "connection": "V-ます形 ＋ ながら",
        "meaning": "同时：一边…一边… / while doing, at the same time",
    },
    {
        "level": "N3",
        "pattern": "〜ながらも",
        "regex": r"ながらも",
        "connection": "V-ます形 / adj ＋ ながらも",
        "meaning": "逆接：虽然…但… / although, even though",
    },
    {
        "level": "N3",
        "pattern": "〜てみる",
        "regex": r"[てで]みる|[てで]みた|[てで]みて|[てで]みよう",
        "connection": "V-て形 ＋ みる",
        "meaning": "尝试：试着做… / try doing",
    },
    {
        "level": "N3",
        "pattern": "〜てほしい",
        "regex": r"[てで]ほしい|[てで]ほしかった",
        "connection": "V-て形 ＋ ほしい",
        "meaning": "希望他人：希望对方做… / want (someone) to do",
    },
    {
        "level": "N3",
        "pattern": "〜てあげる",
        "regex": r"[てで]あげる|[てで]あげた|[てで]あげよう",
        "connection": "V-て形 ＋ あげる",
        "meaning": "给予：（我）帮别人做… / do (something) for someone",
    },
    {
        "level": "N3",
        "pattern": "〜てくれる",
        "regex": r"[てで]くれる|[てで]くれた|[てで]くれよ|[てで]ください",
        "connection": "V-て形 ＋ くれる",
        "meaning": "给予：（别人）为我做… / someone does something for me",
    },
    {
        "level": "N3",
        "pattern": "〜てもらう",
        "regex": r"[てで]もらう|[てで]もらった|[てで]もらい",
        "connection": "V-て形 ＋ もらう",
        "meaning": "受益：请别人为我做… / have someone do for me",
    },
    {
        "level": "N3",
        "pattern": "〜ところだ",
        "regex": r"ところだ|ところです|ところだった",
        "connection": "V辞書形 / V-た形 / V-ている ＋ ところだ",
        "meaning": "时间节点：正要/正在/刚刚做完 / just about to / in the middle of / just finished",
    },
    {
        "level": "N3",
        "pattern": "〜ばかり",
        "regex": r"ばかり(?!か)",
        "connection": "V-た形 / N ＋ ばかり",
        "meaning": "光是…/刚刚…：只做某事/刚刚完成 / only, just, nothing but",
    },
    {
        "level": "N3",
        "pattern": "〜うちに",
        "regex": r"うちに",
        "connection": "V-ている / N の ＋ うちに",
        "meaning": "趁机：趁着…的时候 / while, before it's too late",
    },
    {
        "level": "N3",
        "pattern": "〜おかげで",
        "regex": r"おかげで|おかげだ|おかげです",
        "connection": "V普通形 / N の ＋ おかげで",
        "meaning": "正面原因：多亏了… / thanks to (positive)",
    },
    {
        "level": "N3",
        "pattern": "〜せいで",
        "regex": r"せいで|せいだ|せいです|せいか",
        "connection": "V普通形 / N の ＋ せいで",
        "meaning": "负面原因：都是因为…（负面）/ because of (negative)",
    },
    {
        "level": "N3",
        "pattern": "〜ほど",
        "regex": r"ほど(?!よい|いい)",
        "connection": "V普通形 / N ＋ ほど",
        "meaning": "程度：越…越…/…到…程度 / to the extent that",
    },
    {
        "level": "N3",
        "pattern": "〜さえ〜ば",
        "regex": r"さえ.{0,10}ば|さえあれば|さえすれば",
        "connection": "N ＋ さえ ＋ V-ば形",
        "meaning": "条件：只要…就… / if only, as long as",
    },
    {
        "level": "N3",
        "pattern": "〜かわりに",
        "regex": r"かわりに|代わりに",
        "connection": "V普通形 / N の ＋ かわりに",
        "meaning": "代替：代替…/作为…的代价 / instead of, in exchange for",
    },
    {
        "level": "N3",
        "pattern": "〜ずに",
        "regex": r"ずに(?!は)|ずにいる|ずにいた",
        "connection": "V-ない形（ない→ず） ＋ に",
        "meaning": "不做…而…：不做某事的情况下 / without doing",
    },
    {
        "level": "N3",
        "pattern": "〜による",
        "regex": r"による|によって|によると|によれば",
        "connection": "N ＋ による",
        "meaning": "根据·原因：根据…/由…造成 / due to, according to",
    },
    {
        "level": "N3",
        "pattern": "〜について",
        "regex": r"について|についての|についても",
        "connection": "N ＋ について",
        "meaning": "关于：关于…这件事 / about, concerning",
    },
    {
        "level": "N3",
        "pattern": "〜に対して",
        "regex": r"に対して|に対する|に対しても",
        "connection": "N ＋ に対して",
        "meaning": "对象：针对…/对于… / toward, against, in contrast to",
    },
    {
        "level": "N3",
        "pattern": "〜として",
        "regex": r"として|としての|としても",
        "connection": "N ＋ として",
        "meaning": "身份·立场：作为…（的立场）/ as, in the capacity of",
    },
    {
        "level": "N3",
        "pattern": "〜にとって",
        "regex": r"にとって|にとっての",
        "connection": "N ＋ にとって",
        "meaning": "立场：对…来说 / for, from the standpoint of",
    },
    {
        "level": "N3",
        "pattern": "〜ために",
        "regex": r"ために(?!は)|ための",
        "connection": "V辞書形 / N の ＋ ために",
        "meaning": "目的·原因：为了…/由于… / in order to, because of",
    },
    # ── N2 ──────────────────────────────────────────────────────────
    {
        "level": "N2",
        "pattern": "〜べきだ",
        "regex": r"べきだ|べきです|べきではない|べきじゃない",
        "connection": "V辞書形 ＋ べきだ",
        "meaning": "义务·建议：应该做… / should, ought to",
    },
    {
        "level": "N2",
        "pattern": "〜ざるを得ない",
        "regex": r"ざるを得ない|ざるをえない",
        "connection": "V-ない形（ない→ず） ＋ ざるを得ない",
        "meaning": "不得不：不得不做… / have no choice but to",
    },
    {
        "level": "N2",
        "pattern": "〜にもかかわらず",
        "regex": r"にもかかわらず",
        "connection": "V普通形 / N ＋ にもかかわらず",
        "meaning": "逆接：尽管…却… / despite, in spite of",
    },
    {
        "level": "N2",
        "pattern": "〜どころか",
        "regex": r"どころか",
        "connection": "V普通形 / N ＋ どころか",
        "meaning": "强调否定：别说…了，连…都… / far from, let alone",
    },
    {
        "level": "N2",
        "pattern": "〜ものの",
        "regex": r"ものの",
        "connection": "V普通形 / adj ＋ ものの",
        "meaning": "逆接：虽然…但结果不如预期 / although (but result is unexpected)",
    },
    {
        "level": "N2",
        "pattern": "〜ばかりか",
        "regex": r"ばかりか",
        "connection": "V普通形 / N ＋ ばかりか",
        "meaning": "追加强调：不仅如此还… / not only...but also (emphatic)",
    },
    {
        "level": "N2",
        "pattern": "〜に加えて",
        "regex": r"に加えて|に加え(?=[、。])",
        "connection": "N ＋ に加えて",
        "meaning": "追加：除此之外还加上… / in addition to",
    },
    {
        "level": "N2",
        "pattern": "〜において",
        "regex": r"において|においては|における",
        "connection": "N ＋ において",
        "meaning": "场所·范围（书面语）：在…方面 / in, at (formal)",
    },
    {
        "level": "N2",
        "pattern": "〜に関して",
        "regex": r"に関して|に関する|に関しても",
        "connection": "N ＋ に関して",
        "meaning": "关于（书面语）：关于… / regarding, concerning (formal)",
    },
    {
        "level": "N2",
        "pattern": "〜がちだ",
        "regex": r"がちだ|がちな|がちに|がちで",
        "connection": "V-ます形 / N ＋ がちだ",
        "meaning": "倾向（负面）：容易…/动不动就… / tend to (often negative)",
    },
    # ── N1 ──────────────────────────────────────────────────────────
    {
        "level": "N1",
        "pattern": "〜かねない",
        "regex": r"かねない|かねません",
        "connection": "V-ます形 ＋ かねない",
        "meaning": "危险可能：很可能会（不好的事）/ might possibly (negative)",
    },
    {
        "level": "N1",
        "pattern": "〜かねる",
        "regex": r"かねる|かねます",
        "connection": "V-ます形 ＋ かねる",
        "meaning": "难以：难以做…/做不到 / find it difficult to",
    },
    {
        "level": "N1",
        "pattern": "〜ならではの",
        "regex": r"ならではの|ならでは",
        "connection": "N ＋ ならでは",
        "meaning": "独特：只有…才有的 / unique to, characteristic of",
    },
]

VOCAB_DB = [
    {"word": "確認", "reading": "かくにん", "meaning": "确认 / to confirm", "level": "N3"},
    {"word": "緊張", "reading": "きんちょう", "meaning": "紧张 / nervous, tense", "level": "N3"},
    {"word": "諦める", "reading": "あきらめる", "meaning": "放弃 / to give up", "level": "N3"},
    {"word": "我慢", "reading": "がまん", "meaning": "忍耐 / to endure", "level": "N3"},
    {"word": "仕方ない", "reading": "しかたない", "meaning": "没办法 / can't be helped", "level": "N3"},
    {"word": "心配", "reading": "しんぱい", "meaning": "担心 / worry, concern", "level": "N3"},
    {"word": "気持ち", "reading": "きもち", "meaning": "心情·感觉 / feeling, mood", "level": "N3"},
    {"word": "大切", "reading": "たいせつ", "meaning": "重要·珍贵 / important, precious", "level": "N3"},
    {"word": "正直", "reading": "しょうじき", "meaning": "诚实 / honest, frank", "level": "N3"},
    {"word": "失敗", "reading": "しっぱい", "meaning": "失败 / failure, mistake", "level": "N3"},
    {"word": "成功", "reading": "せいこう", "meaning": "成功 / success", "level": "N3"},
    {"word": "努力", "reading": "どりょく", "meaning": "努力 / effort, endeavor", "level": "N3"},
    {"word": "笑顔", "reading": "えがお", "meaning": "笑脸 / smile, smiling face", "level": "N3"},
    {"word": "涙", "reading": "なみだ", "meaning": "眼泪 / tear, tears", "level": "N3"},
    {"word": "夢", "reading": "ゆめ", "meaning": "梦·梦想 / dream", "level": "N3"},
    {"word": "信じる", "reading": "しんじる", "meaning": "相信 / to believe, trust", "level": "N3"},
    {"word": "感謝", "reading": "かんしゃ", "meaning": "感谢 / gratitude, thanks", "level": "N3"},
    {"word": "記憶", "reading": "きおく", "meaning": "记忆 / memory, recollection", "level": "N3"},
    {"word": "想像", "reading": "そうぞう", "meaning": "想象 / imagination", "level": "N3"},
    {"word": "決める", "reading": "きめる", "meaning": "决定 / to decide", "level": "N3"},
    {"word": "伝える", "reading": "つたえる", "meaning": "传达 / to convey, tell", "level": "N3"},
    {"word": "気づく", "reading": "きづく", "meaning": "注意到 / to notice, realize", "level": "N3"},
    {"word": "慌てる", "reading": "あわてる", "meaning": "慌张 / to panic, rush", "level": "N3"},
    {"word": "落ち着く", "reading": "おちつく", "meaning": "冷静 / to calm down", "level": "N3"},
    {"word": "謝る", "reading": "あやまる", "meaning": "道歉 / to apologize", "level": "N3"},
    {"word": "許す", "reading": "ゆるす", "meaning": "原谅 / to forgive, allow", "level": "N3"},
    {"word": "迷惑", "reading": "めいわく", "meaning": "麻烦·困扰 / trouble, nuisance", "level": "N3"},
    {"word": "関係", "reading": "かんけい", "meaning": "关系 / relationship, connection", "level": "N3"},
    {"word": "様子", "reading": "ようす", "meaning": "样子·状态 / appearance, state", "level": "N3"},
    {"word": "理由", "reading": "りゆう", "meaning": "理由 / reason, cause", "level": "N3"},
    {"word": "経験", "reading": "けいけん", "meaning": "经验 / experience", "level": "N3"},
    {"word": "予定", "reading": "よてい", "meaning": "预定·计划 / plan, schedule", "level": "N3"},
    {"word": "準備", "reading": "じゅんび", "meaning": "准备 / preparation", "level": "N3"},
    {"word": "連絡", "reading": "れんらく", "meaning": "联络 / contact, communication", "level": "N3"},
    {"word": "集中", "reading": "しゅうちゅう", "meaning": "集中 / concentration, focus", "level": "N3"},
]
